---
network:
  - name: cardano-node

objectstorage:
  - name: "cardano-node-cloudinit-metadata"
    acl: "public-read"
    logging: true
    # Must be specified manually in terraform/cardano-infrastructure/versions.tf backend block
  - name: "cardano-infrastructure-tfstate"
    logging: true
    bootstrap: true

nosql:
    # Must be specified manually in terraform/cardano-infrastructure/versions.tf backend block
  - name: "terraform-state-locking"
    billing_mode: "PAY_PER_REQUEST"
    bootstrap: true
