---
ipaddress:
  - name: cardano-node

network:
  - name: cardano-node

objectstorage:
  # The 'terraform_state: true' flag tells the Terraform backend setup script to create this bucket
  - name: "cardano-infrastructure-tfstate"
    logging: true
    terraform_state: true
  - name: "cardano-node-cloudinit-metadata"
    acl: "public-read"
    logging: true

nosql:
  - name: "terraform-state-locking"
    billing_mode: "PAY_PER_REQUEST"
    terraform_state: true
